task: Cifar10 #Cifar10
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 230
poison_epoch: 200
poison_epoch_stop: 401
save_on_epochs: [] # [30, 50, 80, 100, 120, 150, 170, 200]
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.5
backdoor_label: 8

resume_model: resume_model/model_epoch_200.pt.tar
#  model_cifar10_epoch_465.pt.tar
#  model_epoch_200.pt.tar

save_model: False
log: True

transform_train: True

fl: True
fl_no_models: 100
fl_local_epochs: 2
fl_poison_epochs: 15
fl_total_participants: 100
fl_eta: 0.8 # 0.8
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 20
fl_weight_scale: 5
fl_adv_group_size: 5
# fl_single_epoch_attack: 200

attack: ThrDFed  #LIE   labelflipping  ModelReplace   frequency  Spectral  MixAttack Chameleon           CerP DBA  CerP   DataFreeAttack CerP frequency
defense: MARS   # FreqFed  FedAvg FedAvg  Foolsgold LightFed FLAME  LightFed '' ''  LightFed   'FLDetector' 'RFLBAT'  'Deepsight' 'FedCLP' ''     Krum                                                   Indicator 'Indicator'             'FLAME'       'FedAvg'   'Median' 'TriMean'    'Foolsgold'    'FedAvg'
fl_num_neurons: 5
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1
epsilon: 0.03
kappa: 5
adaptive_attack_factor: 0.0001