task: MNIST
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 30
poison_epoch: 1
poison_epoch_stop: 100
save_on_epochs: # [10, 20, 30, 40, 50]
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.5
backdoor_label: 8

resume_model: #resume_model/mnist_model_epoch_10.pt.tar   #mnist_model_epoch_10.pt.tar

save_model: False
log: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 20
fl_local_epochs: 2
fl_poison_epochs: 15
fl_total_participants: 20
fl_eta: 1
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 4
fl_weight_scale: 5
fl_adv_group_size: 2
# fl_single_epoch_attack: 20

attack: ThrDFed  # CerP   Spectral
defense: LightFed   # 'Krum' 'RFLBAT' 'FedAvg' 'LightFed' 'FLAME'  'FLDetector'  'Foolsgold'  'FedCLP'       'FedCLP' 'FLAME'   'Foolsgold'
fl_num_neurons: 8
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1